USE [master]
GO
/****** Object:  Database [Spayce]    Script Date: 02/11/2016 09:57:20 ******/
CREATE DATABASE [Spayce] ON  PRIMARY
( NAME = N'Spyce', FILENAME = N'C:\MSSQL\Data\Spyce.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
LOG ON
( NAME = N'Spyce_log', FILENAME = N'C:\MSSQL\Log\Spyce_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Spayce] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Spayce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Spayce] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Spayce] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Spayce] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Spayce] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Spayce] SET ARITHABORT OFF
GO
ALTER DATABASE [Spayce] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Spayce] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Spayce] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Spayce] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Spayce] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Spayce] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Spayce] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Spayce] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Spayce] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Spayce] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Spayce] SET  DISABLE_BROKER
GO
ALTER DATABASE [Spayce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Spayce] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Spayce] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Spayce] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Spayce] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Spayce] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Spayce] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Spayce] SET  READ_WRITE
GO
ALTER DATABASE [Spayce] SET RECOVERY FULL
GO
ALTER DATABASE [Spayce] SET  MULTI_USER
GO
ALTER DATABASE [Spayce] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Spayce] SET DB_CHAINING OFF
GO
USE [Spayce]
GO
/****** Object:  Schema [setup]    Script Date: 02/11/2016 09:57:20 ******/
CREATE SCHEMA [setup] AUTHORIZATION [dbo]
GO
/****** Object:  Table [setup].[Usuario]    Script Date: 02/11/2016 09:57:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [setup].[Usuario](
      [ID] [bigint] IDENTITY(1,1) NOT NULL,
      [Nome] [nvarchar](100) NOT NULL,
      [Email] [nvarchar](100) NOT NULL,
      [Password] [nvarchar](50) NOT NULL,
      [TipoAutenticacao] [nchar](3) NOT NULL,
      [Cpf] [nchar](3) NOT NULL,
      [Foto] [image] NOT NULL,
CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED
(
      [ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_Usuario_Cpf] ON [setup].[Usuario]
(
      [Cpf] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_Usuario_Email] ON [setup].[Usuario]
(
      [Email] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO